INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (1, '1', null, 'My');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (2, '2', null, 'Viet Nam');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (3, '3', null, 'Singapore');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (10, '3', null, 'Viet Nam');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (11, null, null, 'My');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (12, null, null, 'Singapore');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (13, '3', null, 'Viet Nam');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (14, null, null, 'My');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (15, null, null, 'Singapore');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (16, '3', null, 'Viet Nam');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (17, null, null, 'My');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (18, null, null, 'Singapore');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (19, '3', null, 'Viet Nam');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (20, null, null, 'My');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (21, null, null, 'Singapore');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (22, '3', null, 'Viet Nam');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (23, null, null, 'My');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (24, null, null, 'Singapore');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (25, '3', null, 'Viet Nam');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (26, null, null, 'My');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (27, null, null, 'Singapore');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (28, '3', null, 'Viet Nam');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (29, null, null, 'My');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (30, null, null, 'Singapore');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (31, '3', null, 'Viet Nam');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (32, null, null, 'My');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (33, null, null, 'Singapore');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (34, '3', null, 'Viet Nam');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (35, null, null, 'My');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (36, null, null, 'Singapore');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (37, '3', null, 'Viet Nam');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (38, null, null, 'My');
INSERT INTO `tshirt-ecommerce`.country (country_id, code, is_deleted, name) VALUES (39, null, null, 'Singapore');
